import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import styles from './page.module.css'



export const metadata = {
  title: "Big-Data-Retriever",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <nav className={styles.layoutNav}>
        <Link href="/finearts">Fine Arts </Link>
        <Link href="/music">Music(WIP)</Link> 
        <Link href='/music_genre'>Music Genre</Link> 
      </nav>
      <main>{children}</main>
    </body>
  </html>
  );
}
