import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <nav>
        <Link href="/finearts">Fine Arts </Link> | {/* <Link href="/music">Music</Link> */} | <Link href='/music_genre'>Music Genre</Link> 
      </nav>
      <main>{children}</main>
    </body>
  </html>
  );
}
